"""Optional real-LLM backend via any OpenAI-compatible chat API.

Point it at a local server (Ollama, LM Studio, llama.cpp) or a hosted
endpoint with env vars:

    AICHAT_LLM_URL    e.g. http://localhost:11434/v1   (Ollama)
    AICHAT_LLM_MODEL  e.g. llama3.2, qwen2.5, gpt-4o-mini
    AICHAT_LLM_KEY    optional bearer token
    AICHAT_LLM_OFF    set to 1 to force-disable even when configured

When configured + reachable, open-domain replies are generated by the LLM
(with real chat history as messages). Otherwise the built-in transformer
handles them — same architecture real products use: router + fallback.
"""

import json
import logging
import os
import urllib.request
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

_TIMEOUT = 20  # local LLMs can be slow on first token


class LLMClient:
    """Minimal OpenAI-compatible /chat/completions client (stdlib only)."""

    def __init__(self) -> None:
        self.url = os.environ.get("AICHAT_LLM_URL", "").rstrip("/")
        self.model = os.environ.get("AICHAT_LLM_MODEL", "")
        self.key = os.environ.get("AICHAT_LLM_KEY", "")
        self._reachable: Optional[bool] = None  # cached probe

    @property
    def configured(self) -> bool:
        return (
            bool(self.url and self.model)
            and os.environ.get("AICHAT_LLM_OFF") != "1"
        )

    def _post(self, path: str, payload: dict, timeout: int = _TIMEOUT) -> dict:
        req = urllib.request.Request(
            self.url + path,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                **({"Authorization": f"Bearer {self.key}"} if self.key else {}),
            },
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))

    def available(self) -> bool:
        """Probe the endpoint once; cache the result."""
        if not self.configured:
            return False
        if self._reachable is None:
            try:
                req = urllib.request.Request(
                    self.url + "/models",
                    headers=(
                        {"Authorization": f"Bearer {self.key}"}
                        if self.key else {}
                    ),
                )
                with urllib.request.urlopen(req, timeout=5):
                    self._reachable = True
            except Exception as e:
                logger.info("LLM endpoint %s unreachable: %s", self.url, e)
                self._reachable = False
        return self._reachable

    def chat(
        self,
        messages: List[Dict[str, str]],
        max_tokens: int = 160,
        temperature: float = 0.7,
    ) -> Optional[str]:
        """Return the assistant reply text, or None on failure."""
        try:
            data = self._post(
                "/chat/completions",
                {
                    "model": self.model,
                    "messages": messages,
                    "max_tokens": max_tokens,
                    "temperature": temperature,
                },
            )
            return (data["choices"][0]["message"]["content"] or "").strip()
        except Exception as e:
            logger.warning("LLM chat failed: %s", e)
            self._reachable = False  # stop trying this session
            return None
